services:

  redis:
    image: redis:7.0.8-bullseye
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./docker-system/redis/data:/data
    environment:
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    command: redis-server --bind 0.0.0.0 --requirepass D0-N0t-T3ll-4ny0n3
    mem_limit: 8gb
    network_mode: "bridge"
