version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=changeme
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    command: redis-server --bind 0.0.0.0
    mem_limit: 8gb
