version: '3'

services:

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb-server
    ports:
      - 27017:27017
    volumes:
      - ./docker-system/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    command: mongod --bind_ip 0.0.0.0 --auth
    network_mode: "bridge"
