version: '3'

services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongodb.conf:/etc/mongod.conf
      - ./mongod.log:/var/log/mongodb/mongod.log
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iamroot
      - MONGO_INITDB_ROOT_PASSWORD=changemebro
    command: mongod --config /etc/mongod.conf
