version: '3'

services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongod.conf:/etc/mongodb/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iamroot
      - MONGO_INITDB_ROOT_PASSWORD=changemebro
    command: mongod --config /etc/mongodb/mongod.conf
