version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.0"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch
    networks:
      - elasticstacknetwork
  kibana:
    depends_on:
      - elasticsearch
    image: "docker.elastic.co/kibana/kibana:8.6.0"
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - kibana-volume:/usr/share/kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_sys
      - ELASTICSEARCH_PASSWORD=changeme
      - SERVER_BASEPATH=/
    networks:
      - elasticstacknetwork
networks:
  elasticstacknetwork:
    driver: bridge
volumes:
  elasticsearch-volume:
    driver: local
  kibana-volume:
    driver: local
